import React from "react";
import {Movie} from "@/lib/models/Movie";
import {imdbRating, rottenTomatoesIcon} from "@/lib/score";

/** A score chip: translucent like the site's chips, icon then value then a quiet label. */
const CHIP = "inline-flex h-8 items-center gap-1.5 rounded-full bg-black/40 px-3 text-sm ring-1 ring-inset ring-white/15";

/**
 * Metacritic's own colours: 61 and up green, 40-60 yellow, below 40 red.
 * Written out in full: class names built at runtime (`bg-${color}-500`)
 * are never generated by Tailwind, so the old bar had no colour.
 */
function metacriticColour(score: number) {
    if (score >= 61) return "bg-[#66cc33] text-black";
    if (score >= 40) return "bg-[#ffcc33] text-black";
    return "bg-[#ff0000] text-white";
}

/**
 * Every review score a movie has, one chip each, on its own row: IMDb,
 * Rotten Tomatoes critics and audience, Metacritic. Missing scores (0 in
 * this data) are left out rather than shown as "N/A"; the row disappears
 * if there are none. Used on the movie page and in the movie preview.
 *
 * Before: IMDb read only `imdb` (set for ~10% of movies), so most showed
 * "N/A"; Rotten Tomatoes was hidden whenever it had no status (~40%) and
 * always said "Fresh"; Metacritic showed an empty score when missing.
 */
export default function RatingsSection({movie}: { movie: Pick<Movie, "ratings"> }) {
    const r = movie.ratings;
    if (!r) return null;

    const chips: React.ReactNode[] = [];

    const imdb = imdbRating(r);
    if (imdb) chips.push(
        <li key="imdb" className={CHIP} aria-label={`IMDb ${imdb.toFixed(1)} out of 10`}>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src="/imdb.png" alt="" className="h-4 w-auto" />
            <span className="font-semibold">{imdb.toFixed(1)}</span>
            <span aria-hidden className="text-xs text-white/50">/10</span>
        </li>,
    );

    const critics = r.rottenTomatoes ?? 0;
    if (critics > 0) chips.push(
        <li key="rt" className={CHIP} aria-label={`Rotten Tomatoes critics ${Math.round(critics)}%`}>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={rottenTomatoesIcon(critics, r.rottenTomatoesStatus)} alt="" className="size-4 object-contain" />
            <span className="font-semibold">{Math.round(critics)}%</span>
            <span aria-hidden className="text-xs text-white/50">Critics</span>
        </li>,
    );

    const audience = r.rottenTomatoesAudience ?? 0;
    if (audience > 0) chips.push(
        <li key="rt-audience" className={CHIP} aria-label={`Rotten Tomatoes audience ${Math.round(audience)}%`}>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={rottenTomatoesIcon(audience, r.rottenTomatoesAudienceStatus, true)} alt="" className="size-4 object-contain" />
            <span className="font-semibold">{Math.round(audience)}%</span>
            <span aria-hidden className="text-xs text-white/50">Audience</span>
        </li>,
    );

    const metacritic = r.metacritic ?? 0;
    if (metacritic > 0) chips.push(
        <li key="metacritic" className={CHIP} aria-label={`Metacritic ${Math.round(metacritic)}`}>
            <span className={`flex h-5 min-w-5 items-center justify-center rounded-[4px] px-1 text-xs font-bold ${metacriticColour(metacritic)}`}>
                {Math.round(metacritic)}
            </span>
            <span aria-hidden className="text-xs text-white/50">Metacritic</span>
        </li>,
    );

    if (chips.length === 0) return null;
    return <ul aria-label="Ratings" className="flex flex-wrap items-center gap-2">{chips}</ul>;
}
