

services:
  gateway:
    image: api_gateway:0.0.1-SNAPSHOT
    container_name: gateway
    ports:
      - "8760:8760"
    networks:
      - eureka-net
    restart: always
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
  eureka-server:
    image: eureka_server:0.0.1-SNAPSHOT
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - eureka-net
    restart: always
  movie-service:
    image: movie_service:0.0.1-SNAPSHOT
    container_name: movie-service
    ports:
      - "9090:9090"
      - "8080:8080"
    networks:
      - eureka-net
    restart: always
    environment:
      MONGO_DB: MovieDB
      MONGO_URI: mongodb+srv://egflo:108117175aB@serverlessinstance0.stkz2.mongodb.net/?retryWrites=true&w=majoritycd
      EUREKA_URI: http://eureka-server:8761/eureka
  inventory-service:
    image: inventory_service:0.0.1-SNAPSHOT
    container_name: inventory-service
    ports:
      - "9091:9090"
      - "8081:8080"
    networks:
      - eureka-net
    restart: always
    environment:
      MYSQL_HOST: mysql.clmex2hm689e.us-west-2.rds.amazonaws.com
      MYSQL_DATABASE: InventoryDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: 108117175aB
      EUREKA_URI: http://eureka-server:8761/eureka
  order-service:
    image: order_service:0.0.1-SNAPSHOT
    container_name: order-service
    ports:
      - "9092:9090"
      - "8082:8080"
    networks:
      - eureka-net
    restart: always
    environment:
      POSTGRES_HOST: postgres.clmex2hm689e.us-west-2.rds.amazonaws.com
      POSTGRES_DB: OrderDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 108117175aB
      EUREKA_URI: http://eureka-server:8761/eureka
  tax-service:
    image: tax_service:0.0.1-SNAPSHOT
    container_name: tax-service
    ports:
      - "9093:9090"
      - "8083:8080"
    networks:
      - eureka-net
    restart: always
    environment:
      POSTGRES_HOST: postgres.clmex2hm689e.us-west-2.rds.amazonaws.com
      POSTGRES_DB: TaxDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 108117175aB
      EUREKA_URI: http://eureka-server:8761/eureka
  movie-service2:
    image: movie_service:0.0.1-SNAPSHOT
    container_name: movie-service2
    ports:
      - "9094:9090"
      - "8084:8080"
    networks:
      - eureka-net
    restart: always
    environment:
      MONGO_DB: MovieDB
      MONGO_URI: mongodb+srv://egflo:108117175aB@serverlessinstance0.stkz2.mongodb.net/?retryWrites=true&w=majoritycd
      EUREKA_URI: http://eureka-server:8761/eureka
networks:
  eureka-net:
    driver: bridge


