x-image-prefix: &image_prefix 472315148525.dkr.ecr.us-west-2.amazonaws.com/movie_store


services:
  gateway:
    image: &image_prefix/gateway:latest
    container_name: gateway
    ports:
      - "8760:8760"
    networks:
      - eureka-net
    restart: always
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
  eureka-server:
    image: &image_prefix/movie_store/eureka:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - eureka-net
    restart: always
  movie-service:
    image: &image_prefix/movie-service:latest
    container_name: movie-service
    ports:
      - "9090:9090"
      - "8080:8080"
    networks:
      - eureka-net
    restart: always
    environment:
      MONGO_DB: moviedb
      MONGO_URI: mongodb://localhost:27017
      EUREKA_URI: http://eureka-server:8761/eureka
      GRPC_PORT: 9090
  inventory-service:
    image: &image_prefix/inventory-service:latest
    container_name: inventory-service
    ports:
      - "9091:9090"
      - "8081:8080"
    networks:
      - eureka-net
    restart: always
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: inventorydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      EUREKA_URI: http://eureka-server:8761/eureka
      GRPC_PORT: 9090
  order-service:
    image: &image_prefix/order-service:latest
    container_name: order-service
    ports:
      - "9092:9090"
      - "8082:8080"
    networks:
      - eureka-net
    restart: always
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      EUREKA_URI: http://eureka-server:8761/eureka
      GRPC_PORT: 9090
  user-service:
    image: &image_prefix/user-service:latest
    container_name: user-service
    ports:
      - "9093:9090"
      - "8083:8080"
    networks:
      - eureka-net
    restart: always
    environment:
      MONGO_DB: userdb
      MONGO_URI: mongodb://localhost:27017
      EUREKA_URI: http://eureka-server:8761/eureka
      GRPC_PORT: 9090
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m
networks:
  eureka-net:
    driver: bridge