FROM openjdk:18-jdk-alpine

WORKDIR /app

# Copy the generated JAR file to the working directory
COPY ./target/inventory_service-0.0.1-SNAPSHOT.jar /app

EXPOSE 8080
EXPOSE 9090

# Run the JAR file
CMD ["java", "-jar", "inventory_service-0.0.1-SNAPSHOT.jar"]