spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orderDB
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
      hibernate:
          ddl-auto: update
      show-sql: true
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

grpc:
  server:
    port: 9092
  client:
    inventory-grpc-server:
      address: 'discovery:///inventory-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

stripe:
  secret:
    key: ${STRIPE_SECRET}
  public:
    key: ${STRIPE_PUBLIC}