server:
  port: 8760
spring:
  security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri:
            issuer-uri:

  application:
    name: gateway

  cloud:
      gateway:
        globalcors:
            corsConfigurations:
                '[/**]':
                  allowedOriginPatterns: "*"
                  allowedMethods: "*"
                  allowedHeaders: "*"
                  allowCredentials: true
        discovery:
            locator:
              enabled: true
              lowerCaseServiceId: true
        routes:
          - id: ${EUREKA_INSTANCE_HOSTNAME_MOVIE_SERVICE:movie-service}
            uri: lb://${EUREKA_INSTANCE_HOSTNAME_MOVIE_SERVICE:MOVIE-SERVICE}
            predicates:
              - Path=/movies/**
          - id: ${EUREKA_INSTANCE_HOSTNAME_ORDER_SERVICE:order-service}
            uri: lb://${EUREKA_INSTANCE_HOSTNAME_ORDER_SERVICE:ORDER-SERVICE}
            predicates:
              - Path=/orders/**
          - id: ${EUREKA_INSTANCE_HOSTNAME_INVENTORY_SERVICE:inventory-service}
            uri: lb://${EUREKA_INSTANCE_HOSTNAME_INVENTORY_SERVICE:INVENTORY-SERVICE}
            predicates:
              - Path=/inventory/**

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - gateway
          - mappings
          - env
          - health
          - info