server:
  port: 8760
spring:
  security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri:
            issuer-uri:

  application:
    name: gateway-api

  cloud:
      gateway:
          globalcors:
            corsConfigurations:
                '[/**]':
                  allowedOrigins: "http://localhost:3000"
                  allowedMethods: "*"
                  allowedHeaders: "*"
                  allowCredentials: true
          discovery:
            locator:
              enabled: true
              lowerCaseServiceId: true
          routes:
            - id: movie-service
              uri: lb://MOVIE-SERVICE
              predicates:
                - Path=/movies/**
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/orders/**
            - id: inventory-service
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/inventory/**

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - gateway
          - mappings
          - env
          - health
          - info