FROM openjdk:18-jdk-slim

# Install glibc
#RUN apk add --no-cache gcompat

WORKDIR /app
COPY ./target/user_service-0.0.1-SNAPSHOT.jar /app

EXPOSE 8080
EXPOSE 9090

CMD ["java", "-jar", "user_service-0.0.1-SNAPSHOT.jar"]

