import Head from 'next/head'
import {Layout} from "../components/Layout";
import Box from "@mui/material/Box";
import React from "react";
import {Section} from "../components/carousel/Section";
import {Hero} from "../components/hero/Hero";
import {GetServerSideProps} from "next";
import nookies from "nookies";
import Carousel from "../components/carousel/CTEST";

const API_URL_BOOKMARK: string = `/${process.env.NEXT_PUBLIC_MOVIE_SERVICE_NAME}/movie/bookmarks/?sortBy=created&limit=27`;
const API_URL_VOTES: string = `/${process.env.NEXT_PUBLIC_MOVIE_SERVICE_NAME}/movie/all?sortBy=ratings.numOfVotes&limit=27`;
const API_URL_POPULAR: string = `/${process.env.NEXT_PUBLIC_MOVIE_SERVICE_NAME}/movie/all?sortBy=popularity&limit=27`;
const API_URL_BOXOFFICE: string = `/${process.env.NEXT_PUBLIC_MOVIE_SERVICE_NAME}/movie/all?sortBy=revenue&limit=27`;


export default function Home() {

  return (
    <>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


        <Box className="flex flex-col w-full overflow-x-hidden"
             sx={{
                 '&::-webkit-scrollbar': { display: 'none' },
             }}
        >

            <Hero/>

            <Section title={"My Watchlist"} path={API_URL_BOOKMARK} authenticated={true}/>


            <Carousel title={"Top Rated"}
                      path={API_URL_VOTES}
                      authenticated={false}
                      vertical={false}/>

            <Carousel title={"Most Popular"}
                      path={API_URL_POPULAR}
                      authenticated={false}
                      vertical={false}/>

            <Box className="w-full h-96 "/>



        </Box>

    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {


    const cookie = nookies.get(context);
    const token = cookie.token;

    return {
        props: {
            token: token ? token : null
        }
    }
}




Home.getLayout = (page: any) => (
    <Layout>
      {page}
    </Layout>
);