import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Layout} from "../components/Layout";
import Typography from "@mui/material/Typography";
import ScrollPagination from "../components/ScrollPagination";
import {CardStyle} from "../components/CardStyle";
import {ContentType} from "../components/ContentType";
import {ViewType} from "../components/ViewType";
import Box from "@mui/material/Box";
import {auth} from "../utils/firebase";
import React from "react";
import useAuthContext from "../hooks/useAuthContext";
import Section from "../components/Section";
import {theme} from "./_app";
import {Hero} from "../components/hero/Hero";
import {GetServerSideProps} from "next";
import nookies from "nookies";
import axios, {AxiosRequestConfig} from "axios/index";
import {Movie} from "../models/Movie";


const API_URL_BOOKMARK: string = `/${process.env.NEXT_PUBLIC_MOVIE_SERVICE_NAME}/movie/bookmarks/?sortBy=created`;
const API_URL_VOTES: string = `/${process.env.NEXT_PUBLIC_MOVIE_SERVICE_NAME}/movie/all?sortBy=ratings.numOfVotes&limit=26`;
const API_URL_POPULAR: string = `/${process.env.NEXT_PUBLIC_MOVIE_SERVICE_NAME}/movie/all?sortBy=popularity&limit=26`;
const API_URL_BOXOFFICE: string = `/${process.env.NEXT_PUBLIC_MOVIE_SERVICE_NAME}/movie/all?sortBy=revenue`;

export default function Home({token}: {token: string | undefined}) {
    const auth = useAuthContext();

  return (

    <>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



        <Box className="flex flex-col gap-2 overflow-hidden w-full"
            sx={{minWidth: "100%", minHeight: "140vh", backgroundColor: theme.palette.background.default}}
        >
            <Hero/>

            {auth.user ? (
                <Section title={"My List"} path={API_URL_BOOKMARK} token={token}/>
            ) : (null)}

            <Section title={"Popular"} path={API_URL_POPULAR} token={token}/>

            <Section title={"Top Rated"} path={API_URL_VOTES} token={token}/>

            <Section title={"Box Office"} path={API_URL_BOXOFFICE} token={token}/>

        </Box>




    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {


    const cookie = nookies.get(context);
    const token = cookie.token;

    return {
        props: {
            token: token ? token : null
        }
    }
}




Home.getLayout = (page: any) => (
    <Layout>
      {page}
    </Layout>
);