spring:
  application:
    name: ${EUREKA_INSTANCE_HOSTNAME:tax-service}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB:TaxDB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
      hibernate:
          ddl-auto: update
      show-sql: true

server:
  port: ${SERVER_PORT:8083}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: ${PREFER_IP_ADDRESS:true}

grpc:
  server:
    port: ${GRPC_PORT:9093}


management:
  endpoint:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
      enabled: true
  health:
    circuitbreakers:
      enabled: true
    ratelimiter:
      enabled: true

